name: My Top 8
on:
  schedule:
  #runs every hour
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README my top 8 users.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matthewjdegarmo/MyTop8@main
        with:
          Users_list: brrees01, intenseone, EdwardHanlon, packersking, sannae, TylerLeonhardt, matthewjdegarmo, matthewjdegarmo
